CREATE TABLE todo.dbo.USERS (
	ID int IDENTITY(1,1) NOT NULL,
	EMAIL varchar(255) COLLATE Latin1_General_CI_AS NOT NULL,
	PASSWORD varchar(255) COLLATE Latin1_General_CI_AS NOT NULL,
	NAME varchar(100) COLLATE Latin1_General_CI_AS NOT NULL,
	CONSTRAINT PK__USERS__3214EC270E48529E PRIMARY KEY (ID)
);

CREATE TABLE todo.dbo.TASK (
	ID int IDENTITY(1,1) NOT NULL,
	DESCRIPTION varchar(255) COLLATE Latin1_General_CI_AS NULL,
	PRIORITY int NULL,
	CONCLUDED bit NULL,
	FK_USER int NOT NULL,
	CONSTRAINT PK__TASK__3214EC274FDA4B12 PRIMARY KEY (ID),
	CONSTRAINT FK_TASK FOREIGN KEY (FK_USER) REFERENCES todo.dbo.USERS(ID)
);

